# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2022-12-22 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TGA_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('p_id', models.IntegerField(primary_key=True, serialize=False)),
                ('pname', models.CharField(max_length=255)),
                ('ptype', models.CharField(max_length=255)),
                ('rating', models.CharField(max_length=255)),
                ('o_time', models.CharField(max_length=255)),
                ('c_time', models.CharField(max_length=255)),
                ('amount', models.CharField(max_length=255)),
                ('latitude', models.CharField(max_length=255)),
                ('longitude', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255)),
            ],
        ),
    ]
