# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2022-12-29 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TGA_app', '0003_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('m_id', models.IntegerField(primary_key=True, serialize=False)),
                ('sender', models.CharField(max_length=255)),
                ('receiver', models.CharField(max_length=255)),
                ('datetime', models.CharField(max_length=255)),
                ('message', models.TextField()),
            ],
        ),
    ]
