# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2023-05-04 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TGA_app', '0004_chat'),
    ]

    operations = [
        migrations.CreateModel(
            name='FR_Table',
            fields=[
                ('r_id', models.IntegerField(primary_key=True, serialize=False)),
                ('sender_username', models.CharField(max_length=255)),
                ('receiver_username', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('f_id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('friends_name', models.TextField()),
            ],
        ),
    ]
